### ISSUE TITLE
Define commentstring variable for octave files

### ISSUE THREAD

**Issue by jrwrigh** [gnu-octave/vim-octave#2]
*So this is slightly convoluted, but I think the cleanest fix would be done to this package.*

### Plugins Involved:
 - vim-octave
 - vim-polyglot
 - vim-commentary

### Current behavior:
Use vim-commentary to comment a line (ie. `gcc`) wraps the line in `/*  ..... */` instead of the Octave/Matlab comment character `%`
 
### Expected behavior:
Use `gcc` to get the normal comment character.
 
### Solution: Set `commentstring`
So before your package was added to `vim-polyglot`, my `*.m` files would be interpreted as Matlab files, which [set the `commentstring` variable](https://github.com/vim/vim/blob/master/runtime/ftplugin/matlab.vim#L27). However, now the file is recognized as octave, and thus skips over the matlab ftplugin.
 
Since you plugin doesn't set the variable is gets set to it's default of `/*%s*/` (instead of matlab's `%\ %s`). 
vim-commentary uses the `commentstring` variable to get how it will determine the comment character, so it doesn't use the correct character to do a comment.
 
I think the cleanest solution is to create a `ftplugin/octave.vim` file just to have a `setlocal commentstring='%\ %s'`, that way it fixes my problem (once it's added to vim-polyglot) and also anyone who uses this plugin and vim-commentary.

**Comment by McSinyx** [comment]
Thanks for reporting the issue.  Since you've figured out the fix, feel free to file a PR.  Otherwise, I'll be back as soon as possible to patch it myself, but my personal life doesn't leave me much free time lately :grinning:
