### ISSUE TITLE
Support DESCRIPTION

### ISSUE THREAD

**Issue by Freed-Wu** [gnu-octave/vim-octave#4]
<https://docs.octave.org/latest/The-DESCRIPTION-File.html> Use yaml as `DESCRIPTION`. Why not add

```vim
  autocmd BufNewFile,BufRead DESCRIPTION setfiletype yaml
```

to

`ftdetect/octave.vim`?

**Comment by McSinyx** [comment]
There is no reason.  I only picked this up for a course
and hasn't touched Octave since.  If interested, I can transfer
this repo to you for more active maintenance.

**Comment by Freed-Wu** [comment]
> If interested, I can transfer
this repo to you for more active maintenance.

:+1: It will be good.

**Comment by Freed-Wu** [comment]
> If interested, I can transfer
this repo to you for more active maintenance.

:+1: It will be good. I am a member of <https://github.com/gnu-octave> organization and I think transfering this repo to the organization can let more people find it.

**Comment by McSinyx** [comment]
Makes sense, but I am not a member.  You will need to accept
the transfer to your account and then move it again.
